### ISSUE TITLE
Hide "Pick layout" and layout switcher if there is only one layout available

### ISSUE THREAD

**Issue by glombek** [PerplexDigital/Perplex.ContentBlocks#8] opened 2020-06-02 17:29 UTC
Would it be possible to hide the "Pick layout" button in the add dialog and the carousel within the block editor if there is only one available layout?

**Comment by PerplexDaniel** [comment] 2020-06-03 07:12
Duplicate of #3, reopen and discuss there if you want. It's not unreasonable but it's inconsistent if a button/carousel sometimes shows and sometimes does not. If this will be implemented it should be a config option (default off).

**Closed by PerplexDaniel** 2020-06-03 07:12 UTC

**Comment by glombek** [comment] 2020-07-02 09:26
This issue should not be closed due to inactivity - these will take time to fix but remain severe accessibility issues.
