### ISSUE TITLE
Nested content item validation not firing

### ISSUE THREAD

**Issue by chrisdent14** [PerplexDigital/Perplex.ContentBlocks#17] opened 2020-06-05 14:15 UTC
**Issue**
Validation for Nested content items within Content Blocks is not firing on Save or Save & Publish

**To reproduce:**
Follow steps to create a new content block
When creating Nested Content item for content block, set validation on required fields, for example.
Add Content Block field to document type
Add Content Block to desired page
Do not complete required fields
Save or Save & Publish page

**Versions**
Version 1.4.0
Umbraco version 8.6.1

**Screenshot**
![image](https://user-images.githubusercontent.com/22013176/83886511-11b3dd80-a73f-11ea-8f44-f207d03c6e8c.png)

**Comment by chrisdent14** [comment] 2020-06-05 15:06
@PerplexDaniel Hmmmm. The same happens for me with textstring

![image](https://user-images.githubusercontent.com/22013176/83892404-85a5b400-a746-11ea-9720-7f4394a5289e.png)

**Comment by PerplexDaniel** [comment] 2020-06-05 15:18
@chrisdent14 
Strange. Is the document type of the block (the element type) perhaps set to "Allow varying by culture"? Cause that shouldn't be necessary and may mess with validation somehow. 

If you directly at the Nested Content datatype of your block to your Home page, the validation does trigger? So outside of content blocks? Because on the server we simply use the Nested Content Validator for the validation so that should act the same. We do add some code to render the validation messages client-side, but it should definitely validate on the server and not publish I would imagine.

**Comment by chrisdent14** [comment] 2020-06-05 15:35
@PerplexDaniel None of my nested content doc types are set to 'Allow varying by culture'

If I add the same datatype, as the one referenced in my content block definition, to the same doc type as the one that has content blocks, the validation fires correctly when empty but not within content blocks.

![image](https://user-images.githubusercontent.com/22013176/83895351-7cb6e180-a74a-11ea-90c9-dd468cecd45b.png)

**Comment by PerplexDaniel** [comment] 2020-06-05 15:48
@chrisdent14 Unfortunately I cannot reproduce this (also tried in another installation but no luck), but because the source is available the easiest thing is to just build a Debug version of `master`, throw that DLL in your solution and attach the debugger of the Perplex.ContentBlocks solution to your solution. Then put a breakpoint [in ContentBlocksValidator](https://github.com/PerplexDigital/Perplex.ContentBlocks/blob/master/src/Perplex.ContentBlocks/PropertyEditor/ContentBlocksValidator.cs#L47) and see what's up. I'm really curious but don't know. 

There are only 2 cases when we skip validation:
1) A block is disabled / hidden
2) The structure is set to "Header", then we skip any blocks (if they are still in the property data) or vice versa (structure set to "Blocks" then we do not validate a header). This last scenario can only ever happen if you switch structure on existing data.

Anyway easiest is just to debug yourself I'm afraid :) Keep in mind if you rebuild your solution it will just overwrite the DLL again from the NuGet package. 

I'll be off for the weekend but may check back at some point, otherwise next week. Should be fixable though, I have not seen this before myself. You can also try a fresh install and throw [`Example.cs`](https://github.com/PerplexDigital/Perplex.ContentBlocks/blob/master/src/DemoWebsite/Example.cs) in `App_Code` to generate doctype + datatype for you, then just add Perplex.ContentBlocks to the homepage. That's usually how I test and then this issue should definitely not appear.

**Comment by chrisdent14** [comment] 2020-06-05 15:58
@PerplexDaniel I will debug the master version of 1.4.0 and let you know how it goes. 

Thanks for your help. Have a good weekend 👍

**Comment by chrisdent14** [comment] 2020-06-05 21:26
@PerplexDaniel I managed to find and resolve the issue!

The problem was with my ContentBlockDefinition. The way I was defining the block meant that DataTypeId and DataTypeKey were both being set, however DataTypeId was set to 0. 

This meant that at line 81 of the ContentBlocksValidator class ([https://github.com/PerplexDigital/Perplex.ContentBlocks/blob/master/src/Perplex.ContentBlocks/PropertyEditor/ContentBlocksValidator.cs#L81]), the condition was passing because `definition.DataTypeId` was set to a value of 0 and not null. This meant it set `dataType` to null as the Data Type Service could obviously not find a corresponding Data Type.

Code snippet in question:
```
IDataType dataType = null;
if (definition.DataTypeId is int dataTypeId)
{
    dataType = _dataTypeService.GetDataType(dataTypeId);
}
else if (definition.DataTypeKey is Guid dataTypeKey)
{
    dataType = _dataTypeService.GetDataType(dataTypeKey);
}

if (dataType == null)
{
    return Enumerable.Empty<ValidationResult>();
}
```

Once I added a check to set DataTypeId to null in my code if no DataTypeId was supplied and reran the definitions, the validation all fires as expected

I considered a pull request to do a null check on the `definition.DataTypeId` above but wasn't sure if this was by design.

Thanks for your help on this and if you'd like me to submit a pull request as suggested, let me know!

Thanks,
Chris

**Comment by PerplexDaniel** [comment] 2020-06-06 09:31
@chrisdent14 Great you solved it yourself 🎉 !

> I considered a pull request to do a null check on the definition.DataTypeId above but wasn't sure if this was by design.

Well we currently check if `DataTypeId` is **not null** with the line below, and if that's the case use it. If it is null we will move to the `DataTypeKey` instead. 
```csharp
// true only when DataTypeId is NOT NULL and assigns its int value to dataTypeId
if (definition.DataTypeId is int dataTypeId)
```
Where would you suggest a `null` check of `DataTypeId`?

Because `DataTypeId` is a nullable type (`int?`), any non-null value is a valid value (including 0), so I will use that. 

In your case, I assume you explicitly assigned `0` to the `DataTypeId` property of your definition, something like this?
```csharp
new ContentBlockDefinition
{   
    ...
    DataTypeId = 0, // <- THIS
    DataTypeKey = new Guid(...),
    ...
};
```

Because when you simply skip the assignment, or you assign `default` (`DataTypeId = default`), the value would end up as `null`, not `0`.

We could add some sort of "definition validator" which checks this, because you should only ever assign either the id OR the key, although I thought that was fairly obvious but I suppose not really 😄 I see there is actually no description of the properties in the class so I will add some comments at those properties describing you really should only provide one of them.

Another thing I will change soon is that client-side we seem to ignore a `DataTypeId` of `0` in a couple of places due to the way JavaScript's `||` operator works but that isn't necessarily intended. 

So in a couple of spots we do something like `var id = dataTypeId || dataTypeKey`, which of course then ignores `0`. So I'll change that to something like `var id = dataTypeId == null ? dataTypeKey : dataTypeId`. In that case, you would have already gotten errors in Umbraco that the content block could not be rendered at all. Failing early would have been good here for sure.

That should prevent this subtle bug for other people. I'll just close this but if you want to respond to some of the things here feel free to just open it again with your response.

**Closed by PerplexDaniel** 2020-06-06 09:31 UTC

**Comment by chrisdent14** [comment] 2020-06-06 11:05
> I considered a pull request to do a null check on the definition.DataTypeId above but wasn't sure if this was by design.

What I meant to say here was: I considered a pull request to add a condition to check definition.DataTypeId was > 0 but wasn't sure if this was by design. It was late and I was tired when I wrote this! Haha

As you suggested, I had explicitly set DataTypeId as 0 as well as setting DataTypeKey to a valid GUID, which is what caused this issue.

> We could add some sort of "definition validator" which checks this, because you should only ever assign either the id OR the key, although I thought that was fairly obvious but I suppose not really

I actually think, per your documentation, that this is quite clear. It was just the implementation I've used to create content block definitions hadn't taken this into account.  However, I suppose property descriptions couldn't hurt 👍 

> Another thing I will change soon is that client-side we seem to ignore a DataTypeId of 0 in a couple of places due to the way JavaScript's || operator works but that isn't necessarily intended.

Yes, I had found that from my debugging last night but hadn't realised this was the intended behaviour in JS here.

Thanks for your time on this issue . Just want to say that I think the package is great and really nice to use so congrats 🎉
