### ISSUE TITLE
Perplex block UI hides grid layout settings

### ISSUE THREAD

**Issue by Wiggee11** [PerplexDigital/Perplex.ContentBlocks#63] opened 2022-06-30 12:09 UTC
The Perplex UI hides the settings cog for grid layouts when in a Perplex block so grid layout settings are not useable.

The grid layout has settings applied which are not accessible when using with a Perplex block.
![perpelx grid](https://user-images.githubusercontent.com/32468062/176673381-aecaafda-a177-49be-8f5a-2ab1efaa54dc.JPG)

Deleting the `umb-editor-sub-header` element, the settings cog is revealed.
![perpelx grid 2](https://user-images.githubusercontent.com/32468062/176673647-5a3e616f-96ae-4fb8-bf64-44bea476412b.JPG)

**Comment by PerplexDaniel** [comment] 2022-07-01 06:26
That's unfortunate, I have not actually seen the Grid being used _inside_ ContentBlocks that's interesting. 

> Deleting the umb-editor-sub-header element, the settings cog is revealed.

Isn't the `umb-editor-sub-header` part of the Grid itself? I don't think that's an element created by our package so it's not like we can just remove that. However there is probably some CSS rule inside the `.perplex-content-blocks` container that hides the grid controls. If you can pinpoint those we can have a look at how to fix that. Of course we can also have a look ourselves at some point but that might take bit longer.

**Comment by Wiggee11** [comment] 2022-07-01 10:45
We create structured blocks as you'd expect but our clients always require the ability to create grid layout blocks.

I had a quick dive into the generated HTML but couldn't quickly identify what CSS was causing the issue. I wasn't sure if the `um-editor-sub-header` was something generated by Perplex or just using the default Umbraco editor.

I might take a further look into this when I get a spare moment.

**Comment by PerplexDaniel** [comment] 2022-07-06 14:52
@Wiggee11 I cannot reproduce this, I see the settings cogs just fine. Which version of Umbraco and ContentBlocks are you using? I tested in both v8 + v9 in the latest version (2.1.4). I see both cogs without deleting any elements:

![cb](https://user-images.githubusercontent.com/24297947/177579433-24976b2a-3d29-41fc-93e0-574a6bc8a640.gif)

**Comment by Wiggee11** [comment] 2022-07-11 10:54
I am using Umbraco 8.18.4 and Perplex.ContentBlocks 1.7.0. I'll try updating PCB and see what happens...

**Comment by PerplexDaniel** [comment] 2022-09-23 13:40
If you any updates feel free to re-open. Closing this since it has been over 2 months.

**Closed by PerplexDaniel** 2022-09-23 13:40 UTC
Labels: open for PR, waiting for input
